---
- name: Deploy server
  hosts: deploy
  roles:
    - role: preconfig
    # - role: deploy
    # - role: swarm_init
    
- name: Manager
  hosts: managers
  roles:
    - role: preconfig
    # - role: swarm_join