- name: user
  hosts: demo
  any_errors_fatal: true
  tasks:
    - name: Preconfig block
      block:
        - name: Create user
          vars:
            user: aidar
          user:
            name: '{{ user }}'
            state: present
          register: error
          ignore_errors: true
        - name: Install curl
          apt:
            name: curl
            update-cache: yes
          register: error
      become: true
      when: ansible_facts['distribution'] == 'CentOS'
      rescue:
        - name: Some error print
          debug:
            var: error
      always:
        - name: Reboot
          debug:
            msg: 'rebooting'
